FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY worker/go.mod .
COPY worker/go.sum .

RUN go mod download

COPY worker/ .

RUN rm -f go.work

RUN go build -o /worker-service .

FROM alpine:latest AS final

RUN mkdir -p /app/storage && chmod -R 777 /app/storage

COPY --from=builder /worker-service /worker-service

WORKDIR /app

ENTRYPOINT ["/worker-service"]