FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY api/go.mod .
COPY api/go.sum .

RUN go mod download

COPY api/ .

RUN rm -f go.work

RUN go build -o /api-gateway .

FROM alpine:latest AS final

WORKDIR /app

RUN mkdir -p storage && chmod -R 777 storage


COPY --from=builder /api-gateway /api-gateway

EXPOSE 8080

ENTRYPOINT ["/api-gateway"]