apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-worker-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-service-deployment
  
  minReplicaCount: 0 
  maxReplicaCount: 10
  
  pollingInterval: 15
  cooldownPeriod: 300
  
  triggers:
  - type: redis
    metadata:
      listName: "image_processing_queue" 
      # Адреса Redis у форматі CLUSTER-IP:PORT або HOSTNAME:PORT
      address: "10.106.250.135:6379" 
      listLength: "5" 
      enableAuthentication: "false"